export type SiteSettings = {
    site_name?: string;
    site_title?: string;
    site_description?: string;
    site_keywords?: string;
    site_author?: string;
    site_url?: string;
    site_logo?: string | null;
    site_icon?: string | null;
    site_cover_image?: string | null;
    site_favicon?: string | null;
    contact_email?: string;
    contact_phone?: string;
    address?: string;
    facebook_url?: string;
    twitter_url?: string;
    linkedin_url?: string;
    instagram_url?: string;
    meta_title?: string;
    meta_keywords?: string;
    meta_description?: string;
    google_analytics_id?: string;
    maintenance_mode?: string;
    timezone?: string;
    date_format?: string;
    time_format?: string;
    default_language?: string;
    default_user_role?: string;
    currency?: string;
    currency_symbol?: string;
};
